
apiVersion: v1
kind: ConfigMap
metadata:
  name: expose-traefik-dashboard-values
data:
  values.yaml: |
    # Enable the Traefik dashboard and expose it (default: :8080/dashboard)
    ingressRoute:
        dashboard:
          enabled: true
    ports:
      traefik:
        expose: 
          default:
            true # This exposes the Traefik dashboard service
    logs:
      access:
        enabled: true
---
# Referencing built-in Traefik in Rancher Desktop (installed by helm)
#  in order to override the default values and expose the dashboard
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: traefik
      # Using the latest version available in the repository
      # Will it always work to refer to the built-in Traefik in Rancher Desktop?
      # version: 0.0 
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: expose-traefik-dashboard-values
      valuesKey: values.yaml
  