apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.name" . }}-config
  namespace: {{ .Values.namespace }}
data:
  swf.properties: |
   swf.load.complete.config.tables.if.count.less.than=500
   swf.user.password.encrypted=false
   swf.plugins.background.core.workers.numThreads=3
   swf.application.authentication.required=false
   swf.application.requires.registration=true
   swf.host={{ .Values.externalDomain }}
   swf.external.port=443
   swf.external.scheme=https
   swf.jdbc.dbschema=public
   swf.jdbc.dbschema.setonconnection=true
   swf.jdbc.set.dbschema.command=set search_path to 'public'
   swf.jdbc.url=jdbc:postgresql://{{ .Values.database.host }}/{{ .Values.database.dbname }}
   swf.jdbc.driver=org.postgresql.Driver
   swf.jdbc.userid={{ .Values.database.username }}
   swf.jdbc.password={{ .Values.database.password }}
   swf.jdbc.readOnly=false
   swf.api.keys.case=SNAKE
   swf.api.root.required=false
   swf.encryption.support=false
   swf.ftl.dir=src/main/resources/templates
   beckn.auth.enabled=true
   in.succinct.beckn.gateway.subscriber_id={{ .Values.externalDomain }}
   in.succinct.beckn.gateway.public_key_id={{ .Values.externalDomain }}.k1
   in.succinct.onet.country.iso.3=IND
   in.succinct.onet.country.iso.2=IN
   in.succinct.onet.name=onix

