apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-registry
  name: db-registry
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-registry
  template:
    metadata:
      labels:
        app: db-registry
    spec:
      containers:
      - image: postgres:15-alpine
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-registry-data
      volumes:
      - name: db-registry-data
        emptyDir: {} 
