# LOCAVORA changed from Amazon Load Balancer (ALB) to Traefik
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.name" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    {{- if .Values.ingress.target_ip }}
    external-dns.alpha.kubernetes.io/target: {{.Values.ingress.target_ip }}
    {{- end }}

spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "common.name" . }}-svc
                port:
                  number: {{ .Values.service.port }}
{{- end }}