apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: registry-port
      # LOCAVORA added
      nodePort: 30030
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
