apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.name" . }}-logs-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
