# ATTENTION - Resource de Flux qui indique de suivre ./infrastructure/rancher-desktop/kustomization.yaml + ses dépendances
# Ce n'est pas un fichier statique pour Kustomize (même Kind, apiVersion différent)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/rancher-desktop
  prune: true
  wait: true
  timeout: 5m0s