apiVersion: v1
kind: Secret
metadata:
  name: beckn-onix-bap-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  privateKey: {{ .Values.global.bap.publicKey | b64enc | quote }}
  publicKey: {{ .Values.global.bap.privateKey | b64enc | quote }}
