kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "common.name" . }}-efs-storageclass
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.global.efs.fileSystemId }}
  directoryPerms: "755"
