apiVersion: v1
kind: Secret
metadata:
  name: beckn-onix-bpp-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  privateKey: {{ .Values.global.bpp.publicKey | b64enc | quote }}
  publicKey: {{ .Values.global.bpp.privateKey | b64enc | quote }}
