apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: locavora-test
spec:
  chart:
    spec:
      chart: whoami
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
  interval: 5m
  install:
    remediation:
      retries: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # LOCAVORA traefik.ingress.kubernetes.io/router.tls: "true"
    # LOCAVORA traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  name: whoami-ingress
  namespace: locavora-test
spec:
  rules:
  - host: whoami
    http:
      paths:
      - backend:
          service:
            name: whoami
            port:
              number: 80
        path: /
        pathType: Prefix

