apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: locavora-test
spec:
  chart:
    spec:
      chart: whoami
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
  interval: 5m
  install:
    remediation:
      retries: 3

